import { Inter } from 'next/font/google'
import './globals.css'
// import dynamic from 'next/dynamic'

// Components
// const Navbar = dynamic(() => import('@/components/Navbar'), { ssr: false })
// const Footer = dynamic(() => import('@/components/Footer'), { ssr: false })
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'QarirGenerator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
